---
- name: I/O Benchmark - Docker EC2
  hosts: io_docker
  become: yes

  vars:
    s3_base_path: s3://thesis-logs-dev/io
    container_name: fio_test_container
    io_variants:
      - { label: "write_1M_d1", rw: "write", bs: "1M", iodepth: 1 }
      - { label: "write_1M_d16", rw: "write", bs: "1M", iodepth: 16 }
      - { label: "read_1M_d1", rw: "read", bs: "1M", iodepth: 1 }
      - { label: "read_1M_d16", rw: "read", bs: "1M", iodepth: 16 }
      - { label: "write_4k_d1", rw: "write", bs: "4k", iodepth: 1 }
      - { label: "write_4k_d16", rw: "write", bs: "4k", iodepth: 16 }
      - { label: "read_4k_d1", rw: "read", bs: "4k", iodepth: 1 }
      - { label: "read_4k_d16", rw: "read", bs: "4k", iodepth: 16 }

  tasks:
    - name: Install required packages (Docker and fio)
      command: yum install -y docker fio

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Cleanup /tmp before tests
      shell: rm -rf /tmp/*

    - name: Execute FIO test per variant with upload and cleanup
      block:
        - name: Create fio definition file for {{ item.label }}
          copy:
            dest: "/tmp/fio_{{ item.label }}.fio"
            content: |
              [benchmark]
              name=IO Test - {{ item.label }}
              filename=/mnt/test_{{ item.label }}.dat
              ioengine=libaio
              direct=1
              bs={{ item.bs }}
              size=1G
              rw={{ item.rw }}
              iodepth={{ item.iodepth }}
              numjobs=1
              runtime=60
              time_based

        - name: Run fio in Docker for {{ item.label }}
          shell: |
            docker run --rm --name {{ container_name }}_{{ item.label }} \
            -v /tmp:/mnt \
            amazonlinux:2 \
            sh -c "yum install -y fio > /dev/null && fio /mnt/fio_{{ item.label }}.fio > /mnt/io_output_{{ item.label }}_docker.log"

        - name: Upload fio result log to S3 for {{ item.label }}
          shell: aws s3 cp "/tmp/io_output_{{ item.label }}_docker.log" "{{ s3_base_path }}/io_output_{{ item.label }}_docker.log"

        - name: Remove fio log file after upload for {{ item.label }}
          file:
            path: "/tmp/io_output_{{ item.label }}_docker.log"
            state: absent

        - name: Remove fio data file after test for {{ item.label }}
          file:
            path: "/tmp/test_{{ item.label }}.dat"
            state: absent

        - name: Remove fio definition file after test for {{ item.label }}
          file:
            path: "/tmp/fio_{{ item.label }}.fio"
            state: absent

      loop: "{{ io_variants }}"
