---
- name: I/O Benchmark - Native EC2
  hosts: io_native
  become: yes

  vars:
    s3_base_path: s3://thesis-logs-dev/io
    io_variants:
      - { label: "write_1M_d1", rw: "write", bs: "1M", iodepth: 1 }
      - { label: "write_1M_d16", rw: "write", bs: "1M", iodepth: 16 }
      - { label: "read_1M_d1", rw: "read", bs: "1M", iodepth: 1 }
      - { label: "read_1M_d16", rw: "read", bs: "1M", iodepth: 16 }
      - { label: "write_4k_d1", rw: "write", bs: "4k", iodepth: 1 }
      - { label: "write_4k_d16", rw: "write", bs: "4k", iodepth: 16 }
      - { label: "read_4k_d1", rw: "read", bs: "4k", iodepth: 1 }
      - { label: "read_4k_d16", rw: "read", bs: "4k", iodepth: 16 }

  tasks:
    - name: Install fio via yum
      command: yum install -y fio

    - name: Cleanup old fio and log files before tests
      shell: rm -f /home/ec2-user/*.dat /home/ec2-user/*.log /home/ec2-user/*.fio

    - name: Run FIO test and cleanup per variant
      include_tasks: fio_variant.yml
      loop: "{{ io_variants }}"
      loop_control:
        loop_var: item
