---
- name: I/O Benchmark - Docker EC2
  hosts: io_docker
  become: yes

  vars:
    s3_base_path: s3://thesis-logs-dev/io
    container_name: fio_test_container

  tasks:
    - name: Install required packages (Docker and fio)
      command: yum install -y docker fio

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run 8 fio benchmark variants (docker)
      block:
        - name: Create fio file {{ label }}
          copy:
            dest: "/tmp/fio_{{ label }}.fio"
            content: |
              [benchmark]
              name=IO Test - {{ label }}
              filename=/mnt/test_{{ label }}.dat
              ioengine=libaio
              direct=1
              bs={{ bs }}
              size=1G
              rw={{ rw }}
              iodepth={{ iodepth }}
              numjobs=1
              runtime=60
              time_based

        - name: Run fio test in Docker for {{ label }}
          shell: |
            docker run --rm --name {{ container_name }}_{{ label }}               -v /tmp:/mnt               amazonlinux:2               sh -c "yum install -y fio > /dev/null && fio /mnt/fio_{{ label }}.fio > /mnt/io_output_{{ label }}_docker.log"

        - name: Upload fio output for {{ label }} to S3
          shell: aws s3 cp "/tmp/io_output_{{ label }}_docker.log" "{{ s3_base_path }}/io_output_{{ label }}_docker.log"

      loop:
        - { label: "write_1M_d1", rw: "write", bs: "1M", iodepth: 1 }
        - { label: "write_1M_d16", rw: "write", bs: "1M", iodepth: 16 }
        - { label: "read_1M_d1", rw: "read", bs: "1M", iodepth: 1 }
        - { label: "read_1M_d16", rw: "read", bs: "1M", iodepth: 16 }
        - { label: "write_4k_d1", rw: "write", bs: "4k", iodepth: 1 }
        - { label: "write_4k_d16", rw: "write", bs: "4k", iodepth: 16 }
        - { label: "read_4k_d1", rw: "read", bs: "4k", iodepth: 1 }
        - { label: "read_4k_d16", rw: "read", bs: "4k", iodepth: 16 }
