---
- name: I/O Benchmark - Docker EC2
  hosts: io_docker
  become: yes

  vars:
    s3_base_path: s3://thesis-logs-dev/io
    container_name: fio_test_container
    io_variants:
      - { label: "write_1M_d1", rw: "write", bs: "1M", iodepth: 1 }
      - { label: "write_1M_d16", rw: "write", bs: "1M", iodepth: 16 }
      - { label: "read_1M_d1", rw: "read", bs: "1M", iodepth: 1 }
      - { label: "read_1M_d16", rw: "read", bs: "1M", iodepth: 16 }
      - { label: "write_4k_d1", rw: "write", bs: "4k", iodepth: 1 }
      - { label: "write_4k_d16", rw: "write", bs: "4k", iodepth: 16 }
      - { label: "read_4k_d1", rw: "read", bs: "4k", iodepth: 1 }
      - { label: "read_4k_d16", rw: "read", bs: "4k", iodepth: 16 }

  tasks:
    - name: Install required packages (Docker and fio)
      command: yum install -y docker fio

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Cleanup /tmp before tests
      shell: rm -rf /tmp/*

    - name: Execute Docker FIO test with upload and cleanup per variant
      include_tasks: fio_variant_docker.yml
      loop: "{{ io_variants }}"
      loop_control:
        loop_var: item
