---
- name: Uruchomienie PostgreSQL 13 natywnie
  hosts: all
  become: yes

  tasks:
    - name: Włącz PostgreSQL 13 przez amazon-linux-extras
      command: amazon-linux-extras enable postgresql13

    - name: Zainstaluj PostgreSQL 13 i narzędzia
      command: yum install -y postgresql postgresql-server postgresql-contrib

    - name: Zainstaluj pip
      command: yum install -y python3-pip

    - name: Zainstaluj psycopg2
      command: pip3 install psycopg2-binary

    - name: Inicjalizuj bazę danych PostgreSQL
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Uruchom i włącz PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Utwórz bazę testową benchmarkdb
      become_user: postgres
      postgresql_db:
        name: benchmarkdb

    - name: Testy pgbench - warianty native
      block:
        - name: Inicjalizuj pgbench - {{ label }}
          become_user: postgres
          shell: pgbench -i -s {{ scale }} benchmarkdb

        - name: Uruchom test pgbench - {{ label }}
          become_user: postgres
          shell: pgbench -c {{ clients }} -j {{ threads }} -T 60 benchmarkdb > /var/lib/pgsql/pg_result_{{ label }}.log

        - name: Wyślij log do S3 - {{ label }}
          command: aws s3 cp /var/lib/pgsql/pg_result_{{ label }}.log s3://thesis-logs-dev/postgres/output_pg_native_{{ label }}.log
      loop:
        - { label: "1c_1j_s1", clients: 1, threads: 1, scale: 1 }
        - { label: "5c_2j_s1", clients: 5, threads: 2, scale: 1 }
        - { label: "10c_4j_s1", clients: 10, threads: 4, scale: 1 }
        - { label: "20c_4j_s1", clients: 20, threads: 4, scale: 1 }
        - { label: "50c_8j_s1", clients: 50, threads: 8, scale: 1 }
        - { label: "1c_1j_s50", clients: 1, threads: 1, scale: 50 }
        - { label: "5c_2j_s50", clients: 5, threads: 2, scale: 50 }
        - { label: "10c_4j_s50", clients: 10, threads: 4, scale: 50 }
        - { label: "20c_4j_s50", clients: 20, threads: 4, scale: 50 }
        - { label: "50c_8j_s50", clients: 50, threads: 8, scale: 50 }
        - { label: "1c_1j_s100", clients: 1, threads: 1, scale: 100 }
        - { label: "5c_2j_s100", clients: 5, threads: 2, scale: 100 }
        - { label: "10c_4j_s100", clients: 10, threads: 4, scale: 100 }
        - { label: "20c_4j_s100", clients: 20, threads: 4, scale: 100 }
        - { label: "50c_8j_s100", clients: 50, threads: 8, scale: 100 }
