---
- name: Uruchomienie PostgreSQL 13 natywnie
  hosts: all
  become: yes

  tasks:
    - name: Włącz PostgreSQL 13 przez amazon-linux-extras
      command: amazon-linux-extras enable postgresql13

    - name: Zainstaluj PostgreSQL 13 i narzędzia
      command: yum install -y postgresql postgresql-server postgresql-contrib

    - name: Zainstaluj pip
      command: yum install -y python3-pip

    - name: Zainstaluj psycopg2
      command: pip3 install psycopg2-binary

    - name: Inicjalizuj bazę danych PostgreSQL
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Uruchom i włącz PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Utwórz bazę testową benchmarkdb
      become_user: postgres
      postgresql_db:
        name: benchmarkdb

    - name: Inicjalizacja pgbench (50 = ~1M rekordów)
      become_user: postgres
      shell: pgbench -i -s 50 benchmarkdb

    - name: Wykonaj test pgbench (10 klientów, 4 wątki, 60 sek)
      become_user: postgres
      shell: pgbench -c 10 -j 4 -T 60 benchmarkdb > /var/lib/pgsql/pg_result.log

    - name: Wyślij wynik do S3
      command: aws s3 cp /var/lib/pgsql/pg_result.log s3://thesis-logs-dev/postgres/output_pg_native.log
