---
- name: Uruchomienie PostgreSQL 13 w kontenerze Docker
  hosts: all
  become: yes

  tasks:
    - name: Zainstaluj Docker
      command: yum install -y docker

    - name: Uruchom i włącz Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Dodaj ec2-user do grupy docker
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pobierz obraz PostgreSQL 13
      command: docker pull postgres:13

    - name: Usuń istniejący kontener pg-docker (jeśli istnieje)
      shell: docker rm -f pg-docker || true

    - name: Uruchom kontener PostgreSQL
      command: >
        docker run -d --name pg-docker
        -e POSTGRES_PASSWORD=example
        -e POSTGRES_DB=benchmarkdb
        -p 5433:5433
        postgres:13

    - name: Poczekaj na uruchomienie kontenera PostgreSQL
      wait_for:
        port: 5433
        delay: 10

    - name: Zainstaluj klienta PostgreSQL i pgbench
      command: yum install -y postgresql postgresql-contrib

    - name: Inicjalizuj bazę benchmarkdb wewnątrz kontenera
      shell: >
        docker exec -e PGPASSWORD=example pg-docker
        pgbench -i -s 50 -U postgres benchmarkdb

    - name: Wykonaj test pgbench i zapisz wynik do pliku
      shell: >
        docker exec -e PGPASSWORD=example pg-docker
        pgbench -c 10 -j 4 -T 60 -U postgres benchmarkdb > /home/ec2-user/pg_result.log

    - name: Wyślij wynik do S3
      command: aws s3 cp /home/ec2-user/pg_result.log s3://thesis-logs-dev/postgres/output_pg_docker.log
