- hosts: ec2
  become: yes
  tasks:
    - name: Instalacja wymaganych pakietów
      yum:
        name:
          - git
          - python3
          - awscli
        state: present

    - name: Instalacja psutil i numpy
      command: python3 -m pip install psutil numpy


    - name: Klonowanie repozytorium benchmarków
      git:
        repo: 'https://github.com/grzegorzszuper/Praca-magisterska.git'
        dest: /home/ec2-user/benchmark
        version: main

    - name: Uruchomienie benchmark.py dla size 100
      shell: python3 /home/ec2-user/benchmark/tests/benchmark.py --size 100 > /home/ec2-user/benchmark/output_100.log
      args:
        chdir: /home/ec2-user/benchmark


    - name: Uruchomienie benchmark.py dla size 500
      shell: python3 /home/ec2-user/benchmark/tests/benchmark.py --size 500 > /home/ec2-user/benchmark/output_500.log
      args:
        chdir: /home/ec2-user/benchmark

    - name: Uruchomienie benchmark.py dla size 1000
      shell: python3 /home/ec2-user/benchmark/tests/benchmark.py --size 1000 > /home/ec2-user/benchmark/output_1000.log
      args:
        chdir: /home/ec2-user/benchmark


    - name: Wysyłka logów do S3
      command: aws s3 cp /home/ec2-user/benchmark/output_100.log s3://thesis-logs-dev/
    
    - name: Wysyłka logów do S3 (500)
      command: aws s3 cp /home/ec2-user/benchmark/output_500.log s3://thesis-logs-dev/
    
    - name: Wysyłka logów do S3 (1000)
      command: aws s3 cp /home/ec2-user/benchmark/output_1000.log s3://thesis-logs-dev/
