---
- name: Uruchomienie nginx w Dockerze
  hosts: http_docker
  become: yes

  tasks:
    - name: Zainstaluj Docker
      command: amazon-linux-extras install docker -y

    - name: Uruchom i włącz usługę Docker
      command: systemctl enable --now docker

    - name: Stwórz katalog do testowego HTML
      file:
        path: /home/ec2-user/docker-nginx-html
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Stwórz testowy plik HTML
      copy:
        dest: /home/ec2-user/docker-nginx-html/test.html
        content: "Hello from docker nginx!"

    - name: Uruchom kontener nginx-docker
      shell: |
        docker rm -f nginx-docker || true
        docker run -d --name nginx-docker \
          -v /home/ec2-user/docker-nginx-html:/usr/share/nginx/html:ro \
          -p 80:80 nginx
