---
- name: Uruchomienie nginx natywnie na Amazon Linux 2
  hosts: http_native
  become: yes

  tasks:
    - name: Włącz nginx1 przez amazon-linux-extras
      command: amazon-linux-extras enable nginx1

    - name: Zainstaluj nginx przez yum
      command: yum install -y nginx

    - name: Uruchom i włącz nginx
      command: systemctl enable --now nginx

    - name: Stwórz plik testowy
      copy:
        dest: /usr/share/nginx/html/test.html
        content: "Hello from native nginx!"

